export const categories = [
  "All",
  "Restaurants",
  "Salons",
  "Clinics",
  "Repair",
  "Retail",
];

export const businesses = [
  {
    id: 1,
    name: "Lalibela Coffee House",
    category: "Restaurants",
    bio: "Traditional Ethiopian coffee ceremony with fresh-roasted beans, served in a relaxed courtyard setting.",
    rating: 4.8,
    reviewCount: 132,
    location: "Awasa, Sidama",
    featured: true,
  },
  {
    id: 2,
    name: "Bright Smile Dental Clinic",
    category: "Clinics",
    bio: "General and cosmetic dentistry with modern equipment and same-day appointments available.",
    rating: 4.6,
    reviewCount: 58,
    location: "Awasa, Sidama",
    featured: false,
  },
  {
    id: 3,
    name: "Selam Beauty Salon",
    category: "Salons",
    bio: "Full-service salon offering braiding, styling, and skincare treatments for women and men.",
    rating: 4.9,
    reviewCount: 204,
    location: "Awasa, Sidama",
    featured: true,
  },
  {
    id: 4,
    name: "QuickFix Phone Repair",
    category: "Repair",
    bio: "Same-day screen and battery repair for all major phone brands, with a 90-day warranty.",
    rating: 4.3,
    reviewCount: 41,
    location: "Awasa, Sidama",
    featured: false,
  },
  {
    id: 5,
    name: "Habesha Fashion House",
    category: "Retail",
    bio: "Custom-tailored traditional and modern clothing, made to order with a two-week turnaround.",
    rating: 4.7,
    reviewCount: 89,
    location: "Awasa, Sidama",
    featured: false,
  },
  {
    id: 6,
    name: "Green Valley Restaurant",
    category: "Restaurants",
    bio: "Family-style Ethiopian and continental dishes with outdoor seating and live music on weekends.",
    rating: 4.5,
    reviewCount: 167,
    location: "Awasa, Sidama",
    featured: false,
  },
];
